name: "Dependency Review"

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4

      - name: "Dependency Review"
        uses: actions/dependency-review-action@v3
        with:
          # Fail on vulnerabilities of moderate severity or higher
          fail-on-severity: moderate
          # Allow specific licenses (MIT, Apache-2.0, BSD, ISC)
          # deny-licenses: GPL-3.0, AGPL-3.0
          # Check for vulnerabilities in all scopes
          fail-on-scopes: runtime, development
          # Comment on PR with results
          comment-summary-in-pr: true
          # Show full vulnerability details
          # vulnerability-check: true
          # license-check: true
